Add mypy to CI for Type Checking to Help Make the Code Easier to Maintain (#35)
* Add mypy to CI for Type Checking to Help Make the Code Easier to Maintain

Original errors from running "mypy src":
memory_profiling\memory_profile_helpers.py:2: error: Skipping analyzing 'guppy': found module but no type hints or library stubs
memory_profiling\memory_profile_helpers.py:3: error: Cannot find implementation or library stub for module named 'src.config'
memory_profiling\memory_profile_helpers.py:3: error: Cannot find implementation or library stub for module named 'src'
src\wic.py:3: error: Skipping analyzing 'pdfplumber': found module but no type hints or library stubs
src\wic.py:4: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
src\uploadJson.py:2: error: Cannot find implementation or library stub for module named 'src.config'
src\uploadJson.py:15: error: Skipping analyzing 'firebase_admin': found module but no type hints or library stubs
src\file_to_json.py:4: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
src\file_to_json.py:63: error: Cannot find implementation or library stub for module named 'src.census_response'
src\dict_merge.py:185: error: Missing positional argument "d_ls" in call to "main"
src\main.py:8: error: Cannot find implementation or library stub for module named 'src.census_response'
src\main.py:9: error: Cannot find implementation or library stub for module named 'src.file_to_json'
src\main.py:10: error: Cannot find implementation or library stub for module named 'src.wic'
src\main.py:10: error: Cannot find implementation or library stub for module named 'src'
src\census_response.py:1: error: Cannot find implementation or library stub for module named 'src.config'
src\census_response.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
src\census_response.py:2: error: Skipping analyzing 'jenkspy': found module but no type hints or library stubs
src\census_response.py:6: error: Skipping analyzing 'pandas': found module but no type hints or library stubs
src\census_response.py:7: error: Skipping analyzing 'numpyencoder': found module but no type hints or library stubs
src\census_response.py:50: error: Need type annotation for 'df_dict' (hint: "df_dict: Dict[<type>, <type>] = ...")
src\census_response.py:51: error: Need type annotation for 'data_metrics' (hint: "data_metrics: Dict[<type>, <type>] = ...")
src\census_response.py:52: error: Need type annotation for 'data_bins' (hint: "data_bins: Dict[<type>, <type>] = ...")
Found 21 errors in 7 files (checked 7 source files)

-Remove dict_merge.py because it looks unused.

* Fix typo