Add Helpful Message to Cover Common Use Case
If you have the food insecurity xlsx file open while running file_to_json(), it will raise this exception:

xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b',<your computer name>/'

I was able to figure out the cause from: https://stackoverflow.com/a/36752967

-Add a helpful message instead of just the cryptic message because I think opening the file will be the most likely cause of this exception. This does raise an exception during exception handling which causes a lot of logging, but it's an easy way to abort the program, print the original exception and have the helpful message at the bottom.
-Remove the line that added to sys.path since we don't need it in this file